"""
Hazard model for SafeRoute-RL.

A Hazard represents a disaster-related danger region (flood, wildfire,
chemical leak, etc). Hazards can be static or dynamic: they may move
(velocity) and grow (growth_rate) over the course of an episode.

Hazards are intentionally decoupled from any specific data source. In
simulation they are generated by `rl/envs/scenarios.py`. In production
they would be populated by `backend/app/services/hazard_service.py`,
which can be backed by manually entered incidents or an external feed.
Google Maps does NOT supply hazard locations -- it only supplies road
and traffic context.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum


class HazardType(str, Enum):
    FLOOD = "flood"
    WILDFIRE = "wildfire"
    EARTHQUAKE = "earthquake"
    CHEMICAL_LEAK = "chemical_leak"
    LANDSLIDE = "landslide"
    STORM = "storm"
    GENERIC = "generic_emergency_zone"


@dataclass
class Hazard:
    id: str
    x: float  # normalized local coordinate in [0, 1]
    y: float  # normalized local coordinate in [0, 1]
    radius: float  # normalized radius in [0, 1]
    severity: float  # 0.0 (negligible) .. 1.0 (catastrophic)
    hazard_type: HazardType = HazardType.GENERIC
    velocity: tuple[float, float] = (0.0, 0.0)
    growth_rate: float = 0.0  # radius units per step
    active: bool = True
    # A hard_constraint hazard can NEVER be entered by the agent, regardless
    # of the RL policy's preference. Severity alone is a *soft* cost signal;
    # hard_constraint is what the deterministic safety layer enforces.
    hard_constraint: bool = False

    def step(self, dt: float = 1.0, bounds: tuple[float, float] = (0.0, 1.0)) -> None:
        """Advance hazard position/size by one simulation tick."""
        if not self.active:
            return
        vx, vy = self.velocity
        self.x = min(max(self.x + vx * dt, bounds[0]), bounds[1])
        self.y = min(max(self.y + vy * dt, bounds[0]), bounds[1])
        self.radius = max(0.0, self.radius + self.growth_rate * dt)

    def distance_to(self, x: float, y: float) -> float:
        """Euclidean distance from a point to the hazard center."""
        return math.hypot(self.x - x, self.y - y)

    def contains(self, x: float, y: float) -> bool:
        """Whether the point (x, y) lies inside the hazard's danger radius."""
        return self.active and self.distance_to(x, y) <= self.radius

    def risk_at(self, x: float, y: float, falloff: float = 2.0) -> float:
        """
        Continuous risk contribution of this hazard at point (x, y).

        Risk is 0 outside `falloff * radius`, `severity` at the center,
        and decays smoothly in between. This gives the RL agent a dense
        gradient signal instead of only a binary in/out signal, which is
        important because sparse rewards are hard to learn from.
        """
        if not self.active or self.radius <= 0:
            return 0.0
        d = self.distance_to(x, y)
        outer = self.radius * falloff
        if d >= outer:
            return 0.0
        if d <= self.radius:
            return self.severity
        # Linear decay between radius and outer edge.
        frac = 1.0 - (d - self.radius) / (outer - self.radius)
        return self.severity * frac

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "x": self.x,
            "y": self.y,
            "radius": self.radius,
            "severity": self.severity,
            "hazard_type": self.hazard_type.value,
            "velocity": list(self.velocity),
            "growth_rate": self.growth_rate,
            "active": self.active,
            "hard_constraint": self.hard_constraint,
        }
